# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the action will run
# on:
#   push:
#     # Sequence of patterns matched against refs/tags
#     tags:
#       - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

# Just testing for now
on:
  pull_request:
    branches: [ master ]
        

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npx oclif-dev pack:macos
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          #tag_name: ${{ github.ref }}
          #release_name: Release ${{ github.ref }}
          tag_name: test
          release_name: Release ${{ github.run_number }}
          draft: false
          prerelease: false
